export const CREATE_NEW_RECORD = 'CREATE_NEW_RECORD';
export const REMOVE_RECORDS = 'REMOVE_RECORDS';
export const REMOVE_RECORD = 'REMOVE_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const UPDATE_RECORD_SELECTED = 'UPDATE_RECORD_SELECTED';
export const ADD_RECORD = 'ADD_RECORD';
